// Code generated by goctl. DO NOT EDIT.
package types

type AddUserReq struct {
	Mobile   string `json:"mobile"`
	Name     string `json:"name"`
	NickName string `json:"nickName"`
	IsAdmin  int64  `json:"isAdmin"`
}

type AddUserResp struct {
	Code    int64  `json:"code"`
	Message string `json:"message"`
}

type LoginReq struct {
	UserName string `json:"userName"`
	Password string `json:"password"`
}

type LoginResp struct {
	Id           int64  `json:"id"`
	UserName     string `json:"userName"`
	AccessToken  string `json:"token"`
	AccessExpire int64  `json:"accessExpire"`
	RefreshAfter int64  `json:"refreshAfter"`
}
