// Code generated by protoc-gen-go. DO NOT EDIT.
// source: sys.proto

package sys

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type InfoReq struct {
	UserId               int64    `protobuf:"varint,1,opt,name=UserId,proto3" json:"UserId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InfoReq) Reset()         { *m = InfoReq{} }
func (m *InfoReq) String() string { return proto.CompactTextString(m) }
func (*InfoReq) ProtoMessage()    {}
func (*InfoReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_eabf8bab78de1c7d, []int{0}
}

func (m *InfoReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InfoReq.Unmarshal(m, b)
}
func (m *InfoReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InfoReq.Marshal(b, m, deterministic)
}
func (m *InfoReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InfoReq.Merge(m, src)
}
func (m *InfoReq) XXX_Size() int {
	return xxx_messageInfo_InfoReq.Size(m)
}
func (m *InfoReq) XXX_DiscardUnknown() {
	xxx_messageInfo_InfoReq.DiscardUnknown(m)
}

var xxx_messageInfo_InfoReq proto.InternalMessageInfo

func (m *InfoReq) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

type InfoResp struct {
	Avatar               string   `protobuf:"bytes,1,opt,name=avatar,proto3" json:"avatar,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InfoResp) Reset()         { *m = InfoResp{} }
func (m *InfoResp) String() string { return proto.CompactTextString(m) }
func (*InfoResp) ProtoMessage()    {}
func (*InfoResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_eabf8bab78de1c7d, []int{1}
}

func (m *InfoResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InfoResp.Unmarshal(m, b)
}
func (m *InfoResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InfoResp.Marshal(b, m, deterministic)
}
func (m *InfoResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InfoResp.Merge(m, src)
}
func (m *InfoResp) XXX_Size() int {
	return xxx_messageInfo_InfoResp.Size(m)
}
func (m *InfoResp) XXX_DiscardUnknown() {
	xxx_messageInfo_InfoResp.DiscardUnknown(m)
}

var xxx_messageInfo_InfoResp proto.InternalMessageInfo

func (m *InfoResp) GetAvatar() string {
	if m != nil {
		return m.Avatar
	}
	return ""
}

func (m *InfoResp) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type UserAddReq struct {
	Mobile               string   `protobuf:"bytes,1,opt,name=mobile,proto3" json:"mobile,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	NickName             string   `protobuf:"bytes,3,opt,name=nick_name,json=nickName,proto3" json:"nick_name,omitempty"`
	IsAdmin              int64    `protobuf:"varint,4,opt,name=is_admin,json=isAdmin,proto3" json:"is_admin,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserAddReq) Reset()         { *m = UserAddReq{} }
func (m *UserAddReq) String() string { return proto.CompactTextString(m) }
func (*UserAddReq) ProtoMessage()    {}
func (*UserAddReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_eabf8bab78de1c7d, []int{2}
}

func (m *UserAddReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserAddReq.Unmarshal(m, b)
}
func (m *UserAddReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserAddReq.Marshal(b, m, deterministic)
}
func (m *UserAddReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserAddReq.Merge(m, src)
}
func (m *UserAddReq) XXX_Size() int {
	return xxx_messageInfo_UserAddReq.Size(m)
}
func (m *UserAddReq) XXX_DiscardUnknown() {
	xxx_messageInfo_UserAddReq.DiscardUnknown(m)
}

var xxx_messageInfo_UserAddReq proto.InternalMessageInfo

func (m *UserAddReq) GetMobile() string {
	if m != nil {
		return m.Mobile
	}
	return ""
}

func (m *UserAddReq) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UserAddReq) GetNickName() string {
	if m != nil {
		return m.NickName
	}
	return ""
}

func (m *UserAddReq) GetIsAdmin() int64 {
	if m != nil {
		return m.IsAdmin
	}
	return 0
}

type UserListReq struct {
	Current              int64    `protobuf:"varint,1,opt,name=current,proto3" json:"current,omitempty"`
	PageSize             int64    `protobuf:"varint,2,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	NickName             string   `protobuf:"bytes,4,opt,name=nick_name,json=nickName,proto3" json:"nick_name,omitempty"`
	Mobile               string   `protobuf:"bytes,5,opt,name=mobile,proto3" json:"mobile,omitempty"`
	Email                string   `protobuf:"bytes,6,opt,name=email,proto3" json:"email,omitempty"`
	Status               int64    `protobuf:"varint,7,opt,name=status,proto3" json:"status,omitempty"`
	DeptId               int64    `protobuf:"varint,8,opt,name=dept_id,json=deptId,proto3" json:"dept_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserListReq) Reset()         { *m = UserListReq{} }
func (m *UserListReq) String() string { return proto.CompactTextString(m) }
func (*UserListReq) ProtoMessage()    {}
func (*UserListReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_eabf8bab78de1c7d, []int{3}
}

func (m *UserListReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserListReq.Unmarshal(m, b)
}
func (m *UserListReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserListReq.Marshal(b, m, deterministic)
}
func (m *UserListReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserListReq.Merge(m, src)
}
func (m *UserListReq) XXX_Size() int {
	return xxx_messageInfo_UserListReq.Size(m)
}
func (m *UserListReq) XXX_DiscardUnknown() {
	xxx_messageInfo_UserListReq.DiscardUnknown(m)
}

var xxx_messageInfo_UserListReq proto.InternalMessageInfo

func (m *UserListReq) GetCurrent() int64 {
	if m != nil {
		return m.Current
	}
	return 0
}

func (m *UserListReq) GetPageSize() int64 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

func (m *UserListReq) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UserListReq) GetNickName() string {
	if m != nil {
		return m.NickName
	}
	return ""
}

func (m *UserListReq) GetMobile() string {
	if m != nil {
		return m.Mobile
	}
	return ""
}

func (m *UserListReq) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *UserListReq) GetStatus() int64 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *UserListReq) GetDeptId() int64 {
	if m != nil {
		return m.DeptId
	}
	return 0
}

type UserListResp struct {
	Total                int64           `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	List                 []*UserListData `protobuf:"bytes,2,rep,name=list,proto3" json:"list,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *UserListResp) Reset()         { *m = UserListResp{} }
func (m *UserListResp) String() string { return proto.CompactTextString(m) }
func (*UserListResp) ProtoMessage()    {}
func (*UserListResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_eabf8bab78de1c7d, []int{4}
}

func (m *UserListResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserListResp.Unmarshal(m, b)
}
func (m *UserListResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserListResp.Marshal(b, m, deterministic)
}
func (m *UserListResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserListResp.Merge(m, src)
}
func (m *UserListResp) XXX_Size() int {
	return xxx_messageInfo_UserListResp.Size(m)
}
func (m *UserListResp) XXX_DiscardUnknown() {
	xxx_messageInfo_UserListResp.DiscardUnknown(m)
}

var xxx_messageInfo_UserListResp proto.InternalMessageInfo

func (m *UserListResp) GetTotal() int64 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *UserListResp) GetList() []*UserListData {
	if m != nil {
		return m.List
	}
	return nil
}

type UserListData struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	NickName             string   `protobuf:"bytes,3,opt,name=nick_name,json=nickName,proto3" json:"nick_name,omitempty"`
	Avatar               string   `protobuf:"bytes,4,opt,name=avatar,proto3" json:"avatar,omitempty"`
	Password             string   `protobuf:"bytes,5,opt,name=password,proto3" json:"password,omitempty"`
	Salt                 string   `protobuf:"bytes,6,opt,name=salt,proto3" json:"salt,omitempty"`
	Email                string   `protobuf:"bytes,7,opt,name=email,proto3" json:"email,omitempty"`
	Mobile               string   `protobuf:"bytes,8,opt,name=mobile,proto3" json:"mobile,omitempty"`
	Status               int64    `protobuf:"varint,9,opt,name=status,proto3" json:"status,omitempty"`
	DeptId               int64    `protobuf:"varint,10,opt,name=dept_id,json=deptId,proto3" json:"dept_id,omitempty"`
	CreateBy             string   `protobuf:"bytes,11,opt,name=create_by,json=createBy,proto3" json:"create_by,omitempty"`
	CreateTime           string   `protobuf:"bytes,12,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	LastUpdateBy         string   `protobuf:"bytes,13,opt,name=last_update_by,json=lastUpdateBy,proto3" json:"last_update_by,omitempty"`
	LastUpdateTime       string   `protobuf:"bytes,14,opt,name=last_update_time,json=lastUpdateTime,proto3" json:"last_update_time,omitempty"`
	DelFlag              int64    `protobuf:"varint,15,opt,name=del_flag,json=delFlag,proto3" json:"del_flag,omitempty"`
	JobId                int64    `protobuf:"varint,16,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	RoleId               int64    `protobuf:"varint,17,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"`
	RoleName             string   `protobuf:"bytes,18,opt,name=role_name,json=roleName,proto3" json:"role_name,omitempty"`
	JobName              string   `protobuf:"bytes,19,opt,name=job_name,json=jobName,proto3" json:"job_name,omitempty"`
	DeptName             string   `protobuf:"bytes,20,opt,name=dept_name,json=deptName,proto3" json:"dept_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserListData) Reset()         { *m = UserListData{} }
func (m *UserListData) String() string { return proto.CompactTextString(m) }
func (*UserListData) ProtoMessage()    {}
func (*UserListData) Descriptor() ([]byte, []int) {
	return fileDescriptor_eabf8bab78de1c7d, []int{5}
}

func (m *UserListData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserListData.Unmarshal(m, b)
}
func (m *UserListData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserListData.Marshal(b, m, deterministic)
}
func (m *UserListData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserListData.Merge(m, src)
}
func (m *UserListData) XXX_Size() int {
	return xxx_messageInfo_UserListData.Size(m)
}
func (m *UserListData) XXX_DiscardUnknown() {
	xxx_messageInfo_UserListData.DiscardUnknown(m)
}

var xxx_messageInfo_UserListData proto.InternalMessageInfo

func (m *UserListData) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *UserListData) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UserListData) GetNickName() string {
	if m != nil {
		return m.NickName
	}
	return ""
}

func (m *UserListData) GetAvatar() string {
	if m != nil {
		return m.Avatar
	}
	return ""
}

func (m *UserListData) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *UserListData) GetSalt() string {
	if m != nil {
		return m.Salt
	}
	return ""
}

func (m *UserListData) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *UserListData) GetMobile() string {
	if m != nil {
		return m.Mobile
	}
	return ""
}

func (m *UserListData) GetStatus() int64 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *UserListData) GetDeptId() int64 {
	if m != nil {
		return m.DeptId
	}
	return 0
}

func (m *UserListData) GetCreateBy() string {
	if m != nil {
		return m.CreateBy
	}
	return ""
}

func (m *UserListData) GetCreateTime() string {
	if m != nil {
		return m.CreateTime
	}
	return ""
}

func (m *UserListData) GetLastUpdateBy() string {
	if m != nil {
		return m.LastUpdateBy
	}
	return ""
}

func (m *UserListData) GetLastUpdateTime() string {
	if m != nil {
		return m.LastUpdateTime
	}
	return ""
}

func (m *UserListData) GetDelFlag() int64 {
	if m != nil {
		return m.DelFlag
	}
	return 0
}

func (m *UserListData) GetJobId() int64 {
	if m != nil {
		return m.JobId
	}
	return 0
}

func (m *UserListData) GetRoleId() int64 {
	if m != nil {
		return m.RoleId
	}
	return 0
}

func (m *UserListData) GetRoleName() string {
	if m != nil {
		return m.RoleName
	}
	return ""
}

func (m *UserListData) GetJobName() string {
	if m != nil {
		return m.JobName
	}
	return ""
}

func (m *UserListData) GetDeptName() string {
	if m != nil {
		return m.DeptName
	}
	return ""
}

type UserAddResp struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	NickName             string   `protobuf:"bytes,2,opt,name=nick_name,json=nickName,proto3" json:"nick_name,omitempty"`
	Mobile               string   `protobuf:"bytes,3,opt,name=mobile,proto3" json:"mobile,omitempty"`
	Id                   int64    `protobuf:"varint,4,opt,name=id,proto3" json:"id,omitempty"`
	IsAdmin              int64    `protobuf:"varint,5,opt,name=is_admin,json=isAdmin,proto3" json:"is_admin,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserAddResp) Reset()         { *m = UserAddResp{} }
func (m *UserAddResp) String() string { return proto.CompactTextString(m) }
func (*UserAddResp) ProtoMessage()    {}
func (*UserAddResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_eabf8bab78de1c7d, []int{6}
}

func (m *UserAddResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserAddResp.Unmarshal(m, b)
}
func (m *UserAddResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserAddResp.Marshal(b, m, deterministic)
}
func (m *UserAddResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserAddResp.Merge(m, src)
}
func (m *UserAddResp) XXX_Size() int {
	return xxx_messageInfo_UserAddResp.Size(m)
}
func (m *UserAddResp) XXX_DiscardUnknown() {
	xxx_messageInfo_UserAddResp.DiscardUnknown(m)
}

var xxx_messageInfo_UserAddResp proto.InternalMessageInfo

func (m *UserAddResp) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UserAddResp) GetNickName() string {
	if m != nil {
		return m.NickName
	}
	return ""
}

func (m *UserAddResp) GetMobile() string {
	if m != nil {
		return m.Mobile
	}
	return ""
}

func (m *UserAddResp) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *UserAddResp) GetIsAdmin() int64 {
	if m != nil {
		return m.IsAdmin
	}
	return 0
}

type UserUpdateReq struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Email                string   `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Mobile               string   `protobuf:"bytes,3,opt,name=mobile,proto3" json:"mobile,omitempty"`
	Name                 string   `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	NickName             string   `protobuf:"bytes,5,opt,name=nick_name,json=nickName,proto3" json:"nick_name,omitempty"`
	Avatar               string   `protobuf:"bytes,6,opt,name=avatar,proto3" json:"avatar,omitempty"`
	DeptId               int64    `protobuf:"varint,7,opt,name=dept_id,json=deptId,proto3" json:"dept_id,omitempty"`
	LastUpdateBy         string   `protobuf:"bytes,8,opt,name=last_update_by,json=lastUpdateBy,proto3" json:"last_update_by,omitempty"`
	RoleId               int64    `protobuf:"varint,9,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"`
	Status               int64    `protobuf:"varint,10,opt,name=status,proto3" json:"status,omitempty"`
	JobId                int64    `protobuf:"varint,11,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	IsAdmin              int64    `protobuf:"varint,12,opt,name=is_admin,json=isAdmin,proto3" json:"is_admin,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserUpdateReq) Reset()         { *m = UserUpdateReq{} }
func (m *UserUpdateReq) String() string { return proto.CompactTextString(m) }
func (*UserUpdateReq) ProtoMessage()    {}
func (*UserUpdateReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_eabf8bab78de1c7d, []int{7}
}

func (m *UserUpdateReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserUpdateReq.Unmarshal(m, b)
}
func (m *UserUpdateReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserUpdateReq.Marshal(b, m, deterministic)
}
func (m *UserUpdateReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserUpdateReq.Merge(m, src)
}
func (m *UserUpdateReq) XXX_Size() int {
	return xxx_messageInfo_UserUpdateReq.Size(m)
}
func (m *UserUpdateReq) XXX_DiscardUnknown() {
	xxx_messageInfo_UserUpdateReq.DiscardUnknown(m)
}

var xxx_messageInfo_UserUpdateReq proto.InternalMessageInfo

func (m *UserUpdateReq) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *UserUpdateReq) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *UserUpdateReq) GetMobile() string {
	if m != nil {
		return m.Mobile
	}
	return ""
}

func (m *UserUpdateReq) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UserUpdateReq) GetNickName() string {
	if m != nil {
		return m.NickName
	}
	return ""
}

func (m *UserUpdateReq) GetAvatar() string {
	if m != nil {
		return m.Avatar
	}
	return ""
}

func (m *UserUpdateReq) GetDeptId() int64 {
	if m != nil {
		return m.DeptId
	}
	return 0
}

func (m *UserUpdateReq) GetLastUpdateBy() string {
	if m != nil {
		return m.LastUpdateBy
	}
	return ""
}

func (m *UserUpdateReq) GetRoleId() int64 {
	if m != nil {
		return m.RoleId
	}
	return 0
}

func (m *UserUpdateReq) GetStatus() int64 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *UserUpdateReq) GetJobId() int64 {
	if m != nil {
		return m.JobId
	}
	return 0
}

func (m *UserUpdateReq) GetIsAdmin() int64 {
	if m != nil {
		return m.IsAdmin
	}
	return 0
}

type UserUpdateResp struct {
	Pong                 string   `protobuf:"bytes,1,opt,name=pong,proto3" json:"pong,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserUpdateResp) Reset()         { *m = UserUpdateResp{} }
func (m *UserUpdateResp) String() string { return proto.CompactTextString(m) }
func (*UserUpdateResp) ProtoMessage()    {}
func (*UserUpdateResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_eabf8bab78de1c7d, []int{8}
}

func (m *UserUpdateResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserUpdateResp.Unmarshal(m, b)
}
func (m *UserUpdateResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserUpdateResp.Marshal(b, m, deterministic)
}
func (m *UserUpdateResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserUpdateResp.Merge(m, src)
}
func (m *UserUpdateResp) XXX_Size() int {
	return xxx_messageInfo_UserUpdateResp.Size(m)
}
func (m *UserUpdateResp) XXX_DiscardUnknown() {
	xxx_messageInfo_UserUpdateResp.DiscardUnknown(m)
}

var xxx_messageInfo_UserUpdateResp proto.InternalMessageInfo

func (m *UserUpdateResp) GetPong() string {
	if m != nil {
		return m.Pong
	}
	return ""
}

type UserDeleteReq struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserDeleteReq) Reset()         { *m = UserDeleteReq{} }
func (m *UserDeleteReq) String() string { return proto.CompactTextString(m) }
func (*UserDeleteReq) ProtoMessage()    {}
func (*UserDeleteReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_eabf8bab78de1c7d, []int{9}
}

func (m *UserDeleteReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserDeleteReq.Unmarshal(m, b)
}
func (m *UserDeleteReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserDeleteReq.Marshal(b, m, deterministic)
}
func (m *UserDeleteReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserDeleteReq.Merge(m, src)
}
func (m *UserDeleteReq) XXX_Size() int {
	return xxx_messageInfo_UserDeleteReq.Size(m)
}
func (m *UserDeleteReq) XXX_DiscardUnknown() {
	xxx_messageInfo_UserDeleteReq.DiscardUnknown(m)
}

var xxx_messageInfo_UserDeleteReq proto.InternalMessageInfo

func (m *UserDeleteReq) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type UserDeleteResp struct {
	Pong                 string   `protobuf:"bytes,1,opt,name=pong,proto3" json:"pong,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserDeleteResp) Reset()         { *m = UserDeleteResp{} }
func (m *UserDeleteResp) String() string { return proto.CompactTextString(m) }
func (*UserDeleteResp) ProtoMessage()    {}
func (*UserDeleteResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_eabf8bab78de1c7d, []int{10}
}

func (m *UserDeleteResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserDeleteResp.Unmarshal(m, b)
}
func (m *UserDeleteResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserDeleteResp.Marshal(b, m, deterministic)
}
func (m *UserDeleteResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserDeleteResp.Merge(m, src)
}
func (m *UserDeleteResp) XXX_Size() int {
	return xxx_messageInfo_UserDeleteResp.Size(m)
}
func (m *UserDeleteResp) XXX_DiscardUnknown() {
	xxx_messageInfo_UserDeleteResp.DiscardUnknown(m)
}

var xxx_messageInfo_UserDeleteResp proto.InternalMessageInfo

func (m *UserDeleteResp) GetPong() string {
	if m != nil {
		return m.Pong
	}
	return ""
}

// 强加个error
type I18NErrorReq struct {
	Code                 string   `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Lang                 string   `protobuf:"bytes,2,opt,name=lang,proto3" json:"lang,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *I18NErrorReq) Reset()         { *m = I18NErrorReq{} }
func (m *I18NErrorReq) String() string { return proto.CompactTextString(m) }
func (*I18NErrorReq) ProtoMessage()    {}
func (*I18NErrorReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_eabf8bab78de1c7d, []int{11}
}

func (m *I18NErrorReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_I18NErrorReq.Unmarshal(m, b)
}
func (m *I18NErrorReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_I18NErrorReq.Marshal(b, m, deterministic)
}
func (m *I18NErrorReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_I18NErrorReq.Merge(m, src)
}
func (m *I18NErrorReq) XXX_Size() int {
	return xxx_messageInfo_I18NErrorReq.Size(m)
}
func (m *I18NErrorReq) XXX_DiscardUnknown() {
	xxx_messageInfo_I18NErrorReq.DiscardUnknown(m)
}

var xxx_messageInfo_I18NErrorReq proto.InternalMessageInfo

func (m *I18NErrorReq) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *I18NErrorReq) GetLang() string {
	if m != nil {
		return m.Lang
	}
	return ""
}

type I18NErrorResp struct {
	Result               string   `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *I18NErrorResp) Reset()         { *m = I18NErrorResp{} }
func (m *I18NErrorResp) String() string { return proto.CompactTextString(m) }
func (*I18NErrorResp) ProtoMessage()    {}
func (*I18NErrorResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_eabf8bab78de1c7d, []int{12}
}

func (m *I18NErrorResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_I18NErrorResp.Unmarshal(m, b)
}
func (m *I18NErrorResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_I18NErrorResp.Marshal(b, m, deterministic)
}
func (m *I18NErrorResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_I18NErrorResp.Merge(m, src)
}
func (m *I18NErrorResp) XXX_Size() int {
	return xxx_messageInfo_I18NErrorResp.Size(m)
}
func (m *I18NErrorResp) XXX_DiscardUnknown() {
	xxx_messageInfo_I18NErrorResp.DiscardUnknown(m)
}

var xxx_messageInfo_I18NErrorResp proto.InternalMessageInfo

func (m *I18NErrorResp) GetResult() string {
	if m != nil {
		return m.Result
	}
	return ""
}

func init() {
	proto.RegisterType((*InfoReq)(nil), "sys.InfoReq")
	proto.RegisterType((*InfoResp)(nil), "sys.InfoResp")
	proto.RegisterType((*UserAddReq)(nil), "sys.UserAddReq")
	proto.RegisterType((*UserListReq)(nil), "sys.UserListReq")
	proto.RegisterType((*UserListResp)(nil), "sys.UserListResp")
	proto.RegisterType((*UserListData)(nil), "sys.UserListData")
	proto.RegisterType((*UserAddResp)(nil), "sys.UserAddResp")
	proto.RegisterType((*UserUpdateReq)(nil), "sys.UserUpdateReq")
	proto.RegisterType((*UserUpdateResp)(nil), "sys.UserUpdateResp")
	proto.RegisterType((*UserDeleteReq)(nil), "sys.UserDeleteReq")
	proto.RegisterType((*UserDeleteResp)(nil), "sys.UserDeleteResp")
	proto.RegisterType((*I18NErrorReq)(nil), "sys.I18nErrorReq")
	proto.RegisterType((*I18NErrorResp)(nil), "sys.I18nErrorResp")
}

func init() { proto.RegisterFile("sys.proto", fileDescriptor_eabf8bab78de1c7d) }

var fileDescriptor_eabf8bab78de1c7d = []byte{
	// 792 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x55, 0xcd, 0x6e, 0xdb, 0x38,
	0x10, 0x86, 0x25, 0xd9, 0x92, 0xc7, 0x3f, 0x71, 0x98, 0xec, 0xae, 0xe2, 0x3d, 0x24, 0x2b, 0x64,
	0x91, 0x1c, 0x8a, 0x14, 0x49, 0xd1, 0xa0, 0xd7, 0x04, 0x69, 0x0b, 0xa3, 0x45, 0x0e, 0x4e, 0x73,
	0x36, 0x68, 0x8b, 0x31, 0x94, 0xca, 0x92, 0x2a, 0xd2, 0x2d, 0xdc, 0x5b, 0xdf, 0xa5, 0xe7, 0x9e,
	0xfb, 0x1e, 0x7d, 0xa1, 0x62, 0x38, 0xfa, 0x75, 0xec, 0x43, 0x6f, 0x9c, 0x6f, 0x7e, 0xc8, 0xf9,
	0xe6, 0x23, 0x09, 0x6d, 0xb9, 0x92, 0x67, 0x49, 0x1a, 0xab, 0x98, 0x99, 0x72, 0x25, 0xbd, 0xff,
	0xc0, 0x1e, 0x45, 0x0f, 0xf1, 0x58, 0x7c, 0x62, 0x7f, 0x43, 0xeb, 0x5e, 0x8a, 0x74, 0xe4, 0xbb,
	0x8d, 0xa3, 0xc6, 0xa9, 0x39, 0xce, 0x2c, 0xef, 0x12, 0x1c, 0x0a, 0x91, 0x09, 0xc6, 0xf0, 0xcf,
	0x5c, 0xf1, 0x54, 0xc7, 0xb4, 0xc7, 0x99, 0xc5, 0x18, 0x58, 0x11, 0x5f, 0x08, 0xd7, 0xd0, 0xa8,
	0x5e, 0x7b, 0x09, 0x00, 0x56, 0xb8, 0xf2, 0xfd, 0xac, 0xfa, 0x22, 0x9e, 0x06, 0xa1, 0xc8, 0x33,
	0xc9, 0xda, 0x94, 0xc9, 0xfe, 0x85, 0x76, 0x14, 0xcc, 0x3e, 0x4e, 0xb4, 0xc3, 0xd4, 0x0e, 0x07,
	0x81, 0x5b, 0x74, 0x1e, 0x80, 0x13, 0xc8, 0x09, 0xf7, 0x17, 0x41, 0xe4, 0x5a, 0xfa, 0xa0, 0x76,
	0x20, 0xaf, 0xd0, 0xf4, 0x7e, 0x35, 0xa0, 0x83, 0x5b, 0xbe, 0x0f, 0xa4, 0xc2, 0x3d, 0x5d, 0xb0,
	0x67, 0xcb, 0x34, 0x15, 0x91, 0xca, 0x5a, 0xca, 0x4d, 0x36, 0x04, 0x27, 0xe1, 0x73, 0x71, 0x17,
	0x7c, 0xa5, 0x9d, 0xcd, 0x71, 0x61, 0x17, 0x27, 0x32, 0xb7, 0x9d, 0xc8, 0x5a, 0x3b, 0x51, 0xd9,
	0x5a, 0xb3, 0xd6, 0xda, 0x3e, 0x34, 0xc5, 0x82, 0x07, 0xa1, 0xdb, 0xd2, 0x30, 0x19, 0x18, 0x2d,
	0x15, 0x57, 0x4b, 0xe9, 0xda, 0x44, 0x33, 0x59, 0xec, 0x1f, 0xb0, 0x7d, 0x91, 0xa8, 0x49, 0xe0,
	0xbb, 0x0e, 0x39, 0xd0, 0x1c, 0xf9, 0xde, 0x3b, 0xe8, 0x96, 0x4d, 0xc9, 0x04, 0xcb, 0xaa, 0x58,
	0xf1, 0x30, 0xeb, 0x89, 0x0c, 0xf6, 0x3f, 0x58, 0x61, 0x20, 0x95, 0x6b, 0x1c, 0x99, 0xa7, 0x9d,
	0x8b, 0xdd, 0x33, 0x9c, 0x73, 0x9e, 0x76, 0xc3, 0x15, 0x1f, 0x6b, 0xb7, 0xf7, 0xdd, 0x2a, 0xab,
	0x21, 0xcc, 0xfa, 0x60, 0x04, 0xf9, 0xc4, 0x8d, 0xc0, 0xff, 0xf3, 0x79, 0x94, 0x92, 0xb0, 0x6a,
	0x92, 0xd0, 0x14, 0x4b, 0xf9, 0x25, 0x4e, 0xfd, 0x8c, 0x97, 0xc2, 0xc6, 0x4d, 0x24, 0x0f, 0x55,
	0x46, 0x8c, 0x5e, 0x97, 0x6c, 0xd9, 0x6b, 0x6c, 0x65, 0xdc, 0x3a, 0x35, 0x6e, 0x4b, 0x16, 0xdb,
	0xdb, 0x58, 0x84, 0x2a, 0x8b, 0xd8, 0xc3, 0x2c, 0x15, 0x5c, 0x89, 0xc9, 0x74, 0xe5, 0x76, 0xe8,
	0x3c, 0x04, 0x5c, 0xaf, 0xd8, 0x21, 0x74, 0x32, 0xa7, 0x0a, 0x16, 0xc2, 0xed, 0x6a, 0x37, 0x10,
	0xf4, 0x21, 0x58, 0x08, 0x76, 0x0c, 0xfd, 0x90, 0x4b, 0x35, 0x59, 0x26, 0x7e, 0x56, 0xa2, 0xa7,
	0x63, 0xba, 0x88, 0xde, 0x6b, 0xf0, 0x7a, 0xc5, 0x4e, 0x61, 0x50, 0x8d, 0xd2, 0xb5, 0xfa, 0x3a,
	0xae, 0x5f, 0xc6, 0xe9, 0x7a, 0x07, 0xe0, 0xf8, 0x22, 0x9c, 0x3c, 0x84, 0x7c, 0xee, 0xee, 0x90,
	0x34, 0x7d, 0x11, 0xbe, 0x09, 0xf9, 0x9c, 0xfd, 0x05, 0xad, 0xc7, 0x78, 0x8a, 0x0d, 0x0c, 0x68,
	0xbe, 0x8f, 0xf1, 0x74, 0xe4, 0x63, 0x63, 0x69, 0x1c, 0x0a, 0xc4, 0x77, 0xa9, 0x31, 0x34, 0xa9,
	0x31, 0xed, 0xd0, 0xc3, 0x61, 0xd4, 0x18, 0x02, 0xf9, 0x65, 0xc1, 0x62, 0xda, 0xb7, 0xa7, 0x7d,
	0xf6, 0x63, 0x3c, 0xbd, 0xcd, 0x86, 0xaa, 0x99, 0xd2, 0xbe, 0x7d, 0xca, 0x43, 0x00, 0x9d, 0xde,
	0xb7, 0xec, 0x26, 0xe9, 0xcb, 0x2b, 0x93, 0x42, 0x15, 0x8d, 0x6d, 0xaa, 0x30, 0xb6, 0xde, 0x09,
	0xb3, 0x36, 0x37, 0x92, 0x9b, 0x55, 0xc8, 0xad, 0x7a, 0x9b, 0x9b, 0xf5, 0xdb, 0xfc, 0xd3, 0x80,
	0x1e, 0x9e, 0x81, 0x68, 0xc3, 0xfb, 0xbc, 0xae, 0xd5, 0x42, 0x32, 0xc6, 0x66, 0xc9, 0x98, 0x1b,
	0x5f, 0x1a, 0x6b, 0x5b, 0x0f, 0xcd, 0xad, 0xca, 0x6e, 0xd5, 0x94, 0x5d, 0xd1, 0x98, 0x5d, 0xd3,
	0xd8, 0x53, 0x95, 0x38, 0x1b, 0x54, 0x52, 0x99, 0x64, 0xbb, 0x36, 0xc9, 0x52, 0xd3, 0x50, 0xd3,
	0x74, 0xa9, 0x88, 0x4e, 0x55, 0x11, 0x55, 0xea, 0xba, 0x75, 0xea, 0x8e, 0xa1, 0x5f, 0x65, 0x8e,
	0x06, 0x98, 0xc4, 0xd1, 0x3c, 0x1f, 0x20, 0xae, 0xbd, 0x43, 0xe2, 0xf7, 0x46, 0x84, 0x62, 0x23,
	0xbf, 0x79, 0x99, 0x3c, 0x60, 0x4b, 0x99, 0x4b, 0xe8, 0x8e, 0xce, 0x5f, 0x45, 0xaf, 0xd3, 0x34,
	0x4e, 0xb1, 0x0a, 0x03, 0x6b, 0x16, 0xfb, 0x85, 0x56, 0x70, 0x8d, 0x58, 0xc8, 0xa3, 0x79, 0xfe,
	0xaa, 0xe0, 0xda, 0x3b, 0x81, 0x5e, 0x25, 0x8f, 0x3e, 0x97, 0x54, 0xc8, 0x65, 0xa8, 0xf2, 0x2f,
	0x82, 0xac, 0x8b, 0x1f, 0x06, 0x98, 0x77, 0x2b, 0xc9, 0x4e, 0xc0, 0xd1, 0x5f, 0x52, 0xf4, 0x10,
	0xb3, 0xae, 0x7e, 0xe0, 0xb2, 0xaf, 0x6b, 0xd8, 0xab, 0x58, 0x32, 0x61, 0xcf, 0xc0, 0xce, 0xc4,
	0xcb, 0x76, 0x8a, 0x87, 0x90, 0xfe, 0xa1, 0xe1, 0xa0, 0x0e, 0xc8, 0x84, 0x3d, 0xa7, 0xb2, 0xf8,
	0x22, 0xb2, 0x41, 0xed, 0xdd, 0xc4, 0xf8, 0xdd, 0x35, 0x44, 0x26, 0xec, 0x25, 0x7d, 0x6c, 0xc4,
	0x2e, 0x63, 0x45, 0x40, 0x21, 0xd4, 0xe1, 0xde, 0x13, 0xac, 0x4c, 0x23, 0x36, 0x2b, 0x69, 0x05,
	0xff, 0x95, 0xb4, 0x0a, 0xe5, 0xe7, 0xe0, 0xbc, 0x15, 0x4a, 0xb3, 0xc4, 0xe8, 0x30, 0x55, 0xb6,
	0x87, 0x6c, 0x1d, 0x92, 0xc9, 0xb4, 0xa5, 0x3f, 0xf8, 0x17, 0xbf, 0x03, 0x00, 0x00, 0xff, 0xff,
	0x60, 0x39, 0xac, 0x3b, 0xed, 0x07, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// SysClient is the client API for Sys service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SysClient interface {
	// 获取用户信息
	UserInfo(ctx context.Context, in *InfoReq, opts ...grpc.CallOption) (*InfoResp, error)
	// 用户新增
	UserAdd(ctx context.Context, in *UserAddReq, opts ...grpc.CallOption) (*UserAddResp, error)
	// 用户列表
	UserList(ctx context.Context, in *UserListReq, opts ...grpc.CallOption) (*UserListResp, error)
	// 用户更新
	UserUpdate(ctx context.Context, in *UserUpdateReq, opts ...grpc.CallOption) (*UserUpdateResp, error)
	// 用户删除
	UserDelete(ctx context.Context, in *UserDeleteReq, opts ...grpc.CallOption) (*UserDeleteResp, error)
	// todo 后期改进
	GetError(ctx context.Context, in *I18NErrorReq, opts ...grpc.CallOption) (*I18NErrorResp, error)
}

type sysClient struct {
	cc *grpc.ClientConn
}

func NewSysClient(cc *grpc.ClientConn) SysClient {
	return &sysClient{cc}
}

func (c *sysClient) UserInfo(ctx context.Context, in *InfoReq, opts ...grpc.CallOption) (*InfoResp, error) {
	out := new(InfoResp)
	err := c.cc.Invoke(ctx, "/sys.Sys/UserInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sysClient) UserAdd(ctx context.Context, in *UserAddReq, opts ...grpc.CallOption) (*UserAddResp, error) {
	out := new(UserAddResp)
	err := c.cc.Invoke(ctx, "/sys.Sys/UserAdd", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sysClient) UserList(ctx context.Context, in *UserListReq, opts ...grpc.CallOption) (*UserListResp, error) {
	out := new(UserListResp)
	err := c.cc.Invoke(ctx, "/sys.Sys/UserList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sysClient) UserUpdate(ctx context.Context, in *UserUpdateReq, opts ...grpc.CallOption) (*UserUpdateResp, error) {
	out := new(UserUpdateResp)
	err := c.cc.Invoke(ctx, "/sys.Sys/UserUpdate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sysClient) UserDelete(ctx context.Context, in *UserDeleteReq, opts ...grpc.CallOption) (*UserDeleteResp, error) {
	out := new(UserDeleteResp)
	err := c.cc.Invoke(ctx, "/sys.Sys/UserDelete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sysClient) GetError(ctx context.Context, in *I18NErrorReq, opts ...grpc.CallOption) (*I18NErrorResp, error) {
	out := new(I18NErrorResp)
	err := c.cc.Invoke(ctx, "/sys.Sys/GetError", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SysServer is the server API for Sys service.
type SysServer interface {
	// 获取用户信息
	UserInfo(context.Context, *InfoReq) (*InfoResp, error)
	// 用户新增
	UserAdd(context.Context, *UserAddReq) (*UserAddResp, error)
	// 用户列表
	UserList(context.Context, *UserListReq) (*UserListResp, error)
	// 用户更新
	UserUpdate(context.Context, *UserUpdateReq) (*UserUpdateResp, error)
	// 用户删除
	UserDelete(context.Context, *UserDeleteReq) (*UserDeleteResp, error)
	// todo 后期改进
	GetError(context.Context, *I18NErrorReq) (*I18NErrorResp, error)
}

// UnimplementedSysServer can be embedded to have forward compatible implementations.
type UnimplementedSysServer struct {
}

func (*UnimplementedSysServer) UserInfo(ctx context.Context, req *InfoReq) (*InfoResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UserInfo not implemented")
}
func (*UnimplementedSysServer) UserAdd(ctx context.Context, req *UserAddReq) (*UserAddResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UserAdd not implemented")
}
func (*UnimplementedSysServer) UserList(ctx context.Context, req *UserListReq) (*UserListResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UserList not implemented")
}
func (*UnimplementedSysServer) UserUpdate(ctx context.Context, req *UserUpdateReq) (*UserUpdateResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UserUpdate not implemented")
}
func (*UnimplementedSysServer) UserDelete(ctx context.Context, req *UserDeleteReq) (*UserDeleteResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UserDelete not implemented")
}
func (*UnimplementedSysServer) GetError(ctx context.Context, req *I18NErrorReq) (*I18NErrorResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetError not implemented")
}

func RegisterSysServer(s *grpc.Server, srv SysServer) {
	s.RegisterService(&_Sys_serviceDesc, srv)
}

func _Sys_UserInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InfoReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SysServer).UserInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sys.Sys/UserInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SysServer).UserInfo(ctx, req.(*InfoReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sys_UserAdd_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserAddReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SysServer).UserAdd(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sys.Sys/UserAdd",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SysServer).UserAdd(ctx, req.(*UserAddReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sys_UserList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SysServer).UserList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sys.Sys/UserList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SysServer).UserList(ctx, req.(*UserListReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sys_UserUpdate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserUpdateReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SysServer).UserUpdate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sys.Sys/UserUpdate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SysServer).UserUpdate(ctx, req.(*UserUpdateReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sys_UserDelete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserDeleteReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SysServer).UserDelete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sys.Sys/UserDelete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SysServer).UserDelete(ctx, req.(*UserDeleteReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sys_GetError_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(I18NErrorReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SysServer).GetError(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sys.Sys/GetError",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SysServer).GetError(ctx, req.(*I18NErrorReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _Sys_serviceDesc = grpc.ServiceDesc{
	ServiceName: "sys.Sys",
	HandlerType: (*SysServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UserInfo",
			Handler:    _Sys_UserInfo_Handler,
		},
		{
			MethodName: "UserAdd",
			Handler:    _Sys_UserAdd_Handler,
		},
		{
			MethodName: "UserList",
			Handler:    _Sys_UserList_Handler,
		},
		{
			MethodName: "UserUpdate",
			Handler:    _Sys_UserUpdate_Handler,
		},
		{
			MethodName: "UserDelete",
			Handler:    _Sys_UserDelete_Handler,
		},
		{
			MethodName: "GetError",
			Handler:    _Sys_GetError_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "sys.proto",
}
