// Code generated by protoc-gen-go. DO NOT EDIT.
// source: oauth.proto

package oauth

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// 验证手机号是否注册过
type UserCenterValidatePhoneReq struct {
	Code                 string   `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Phone                string   `protobuf:"bytes,2,opt,name=phone,proto3" json:"phone,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserCenterValidatePhoneReq) Reset()         { *m = UserCenterValidatePhoneReq{} }
func (m *UserCenterValidatePhoneReq) String() string { return proto.CompactTextString(m) }
func (*UserCenterValidatePhoneReq) ProtoMessage()    {}
func (*UserCenterValidatePhoneReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_7ce0b12f599e9f07, []int{0}
}

func (m *UserCenterValidatePhoneReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserCenterValidatePhoneReq.Unmarshal(m, b)
}
func (m *UserCenterValidatePhoneReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserCenterValidatePhoneReq.Marshal(b, m, deterministic)
}
func (m *UserCenterValidatePhoneReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserCenterValidatePhoneReq.Merge(m, src)
}
func (m *UserCenterValidatePhoneReq) XXX_Size() int {
	return xxx_messageInfo_UserCenterValidatePhoneReq.Size(m)
}
func (m *UserCenterValidatePhoneReq) XXX_DiscardUnknown() {
	xxx_messageInfo_UserCenterValidatePhoneReq.DiscardUnknown(m)
}

var xxx_messageInfo_UserCenterValidatePhoneReq proto.InternalMessageInfo

func (m *UserCenterValidatePhoneReq) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *UserCenterValidatePhoneReq) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

type UserCenterValidatePhoneResp struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserCenterValidatePhoneResp) Reset()         { *m = UserCenterValidatePhoneResp{} }
func (m *UserCenterValidatePhoneResp) String() string { return proto.CompactTextString(m) }
func (*UserCenterValidatePhoneResp) ProtoMessage()    {}
func (*UserCenterValidatePhoneResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_7ce0b12f599e9f07, []int{1}
}

func (m *UserCenterValidatePhoneResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserCenterValidatePhoneResp.Unmarshal(m, b)
}
func (m *UserCenterValidatePhoneResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserCenterValidatePhoneResp.Marshal(b, m, deterministic)
}
func (m *UserCenterValidatePhoneResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserCenterValidatePhoneResp.Merge(m, src)
}
func (m *UserCenterValidatePhoneResp) XXX_Size() int {
	return xxx_messageInfo_UserCenterValidatePhoneResp.Size(m)
}
func (m *UserCenterValidatePhoneResp) XXX_DiscardUnknown() {
	xxx_messageInfo_UserCenterValidatePhoneResp.DiscardUnknown(m)
}

var xxx_messageInfo_UserCenterValidatePhoneResp proto.InternalMessageInfo

func (m *UserCenterValidatePhoneResp) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

// 发送验证码
type UserCenterSendCodeReq struct {
	AreaCode             string   `protobuf:"bytes,1,opt,name=area_code,json=areaCode,proto3" json:"area_code,omitempty"`
	Phone                string   `protobuf:"bytes,2,opt,name=phone,proto3" json:"phone,omitempty"`
	LanguageCode         string   `protobuf:"bytes,3,opt,name=language_code,json=languageCode,proto3" json:"language_code,omitempty"`
	UserId               string   `protobuf:"bytes,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	SmsBusinessType      int64    `protobuf:"varint,5,opt,name=smsBusiness_type,json=smsBusinessType,proto3" json:"smsBusiness_type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserCenterSendCodeReq) Reset()         { *m = UserCenterSendCodeReq{} }
func (m *UserCenterSendCodeReq) String() string { return proto.CompactTextString(m) }
func (*UserCenterSendCodeReq) ProtoMessage()    {}
func (*UserCenterSendCodeReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_7ce0b12f599e9f07, []int{2}
}

func (m *UserCenterSendCodeReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserCenterSendCodeReq.Unmarshal(m, b)
}
func (m *UserCenterSendCodeReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserCenterSendCodeReq.Marshal(b, m, deterministic)
}
func (m *UserCenterSendCodeReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserCenterSendCodeReq.Merge(m, src)
}
func (m *UserCenterSendCodeReq) XXX_Size() int {
	return xxx_messageInfo_UserCenterSendCodeReq.Size(m)
}
func (m *UserCenterSendCodeReq) XXX_DiscardUnknown() {
	xxx_messageInfo_UserCenterSendCodeReq.DiscardUnknown(m)
}

var xxx_messageInfo_UserCenterSendCodeReq proto.InternalMessageInfo

func (m *UserCenterSendCodeReq) GetAreaCode() string {
	if m != nil {
		return m.AreaCode
	}
	return ""
}

func (m *UserCenterSendCodeReq) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *UserCenterSendCodeReq) GetLanguageCode() string {
	if m != nil {
		return m.LanguageCode
	}
	return ""
}

func (m *UserCenterSendCodeReq) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *UserCenterSendCodeReq) GetSmsBusinessType() int64 {
	if m != nil {
		return m.SmsBusinessType
	}
	return 0
}

type UserCenterSendCodeResp struct {
	Code                 int64             `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg                  string            `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Success              bool              `protobuf:"varint,3,opt,name=success,proto3" json:"success,omitempty"`
	Data                 *SendCodeDataResp `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *UserCenterSendCodeResp) Reset()         { *m = UserCenterSendCodeResp{} }
func (m *UserCenterSendCodeResp) String() string { return proto.CompactTextString(m) }
func (*UserCenterSendCodeResp) ProtoMessage()    {}
func (*UserCenterSendCodeResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_7ce0b12f599e9f07, []int{3}
}

func (m *UserCenterSendCodeResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserCenterSendCodeResp.Unmarshal(m, b)
}
func (m *UserCenterSendCodeResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserCenterSendCodeResp.Marshal(b, m, deterministic)
}
func (m *UserCenterSendCodeResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserCenterSendCodeResp.Merge(m, src)
}
func (m *UserCenterSendCodeResp) XXX_Size() int {
	return xxx_messageInfo_UserCenterSendCodeResp.Size(m)
}
func (m *UserCenterSendCodeResp) XXX_DiscardUnknown() {
	xxx_messageInfo_UserCenterSendCodeResp.DiscardUnknown(m)
}

var xxx_messageInfo_UserCenterSendCodeResp proto.InternalMessageInfo

func (m *UserCenterSendCodeResp) GetCode() int64 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *UserCenterSendCodeResp) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *UserCenterSendCodeResp) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *UserCenterSendCodeResp) GetData() *SendCodeDataResp {
	if m != nil {
		return m.Data
	}
	return nil
}

type SendCodeDataResp struct {
	Succeed              bool                    `protobuf:"varint,1,opt,name=succeed,proto3" json:"succeed,omitempty"`
	Message              string                  `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Result               *SendCodeDataResultResp `protobuf:"bytes,3,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *SendCodeDataResp) Reset()         { *m = SendCodeDataResp{} }
func (m *SendCodeDataResp) String() string { return proto.CompactTextString(m) }
func (*SendCodeDataResp) ProtoMessage()    {}
func (*SendCodeDataResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_7ce0b12f599e9f07, []int{4}
}

func (m *SendCodeDataResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendCodeDataResp.Unmarshal(m, b)
}
func (m *SendCodeDataResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendCodeDataResp.Marshal(b, m, deterministic)
}
func (m *SendCodeDataResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendCodeDataResp.Merge(m, src)
}
func (m *SendCodeDataResp) XXX_Size() int {
	return xxx_messageInfo_SendCodeDataResp.Size(m)
}
func (m *SendCodeDataResp) XXX_DiscardUnknown() {
	xxx_messageInfo_SendCodeDataResp.DiscardUnknown(m)
}

var xxx_messageInfo_SendCodeDataResp proto.InternalMessageInfo

func (m *SendCodeDataResp) GetSucceed() bool {
	if m != nil {
		return m.Succeed
	}
	return false
}

func (m *SendCodeDataResp) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *SendCodeDataResp) GetResult() *SendCodeDataResultResp {
	if m != nil {
		return m.Result
	}
	return nil
}

type SendCodeDataResultResp struct {
	Requestid            string   `protobuf:"bytes,1,opt,name=requestid,proto3" json:"requestid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendCodeDataResultResp) Reset()         { *m = SendCodeDataResultResp{} }
func (m *SendCodeDataResultResp) String() string { return proto.CompactTextString(m) }
func (*SendCodeDataResultResp) ProtoMessage()    {}
func (*SendCodeDataResultResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_7ce0b12f599e9f07, []int{5}
}

func (m *SendCodeDataResultResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendCodeDataResultResp.Unmarshal(m, b)
}
func (m *SendCodeDataResultResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendCodeDataResultResp.Marshal(b, m, deterministic)
}
func (m *SendCodeDataResultResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendCodeDataResultResp.Merge(m, src)
}
func (m *SendCodeDataResultResp) XXX_Size() int {
	return xxx_messageInfo_SendCodeDataResultResp.Size(m)
}
func (m *SendCodeDataResultResp) XXX_DiscardUnknown() {
	xxx_messageInfo_SendCodeDataResultResp.DiscardUnknown(m)
}

var xxx_messageInfo_SendCodeDataResultResp proto.InternalMessageInfo

func (m *SendCodeDataResultResp) GetRequestid() string {
	if m != nil {
		return m.Requestid
	}
	return ""
}

//user start---------------------
type LoginReq struct {
	UserName             string   `protobuf:"bytes,1,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginReq) Reset()         { *m = LoginReq{} }
func (m *LoginReq) String() string { return proto.CompactTextString(m) }
func (*LoginReq) ProtoMessage()    {}
func (*LoginReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_7ce0b12f599e9f07, []int{6}
}

func (m *LoginReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginReq.Unmarshal(m, b)
}
func (m *LoginReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginReq.Marshal(b, m, deterministic)
}
func (m *LoginReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginReq.Merge(m, src)
}
func (m *LoginReq) XXX_Size() int {
	return xxx_messageInfo_LoginReq.Size(m)
}
func (m *LoginReq) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginReq.DiscardUnknown(m)
}

var xxx_messageInfo_LoginReq proto.InternalMessageInfo

func (m *LoginReq) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *LoginReq) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type LoginResp struct {
	Status               string   `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	CurrentAuthority     string   `protobuf:"bytes,2,opt,name=currentAuthority,proto3" json:"currentAuthority,omitempty"`
	Id                   int64    `protobuf:"varint,3,opt,name=id,proto3" json:"id,omitempty"`
	UserName             string   `protobuf:"bytes,4,opt,name=userName,proto3" json:"userName,omitempty"`
	AccessToken          string   `protobuf:"bytes,5,opt,name=AccessToken,proto3" json:"AccessToken,omitempty"`
	AccessExpire         int64    `protobuf:"varint,6,opt,name=AccessExpire,proto3" json:"AccessExpire,omitempty"`
	RefreshAfter         int64    `protobuf:"varint,7,opt,name=RefreshAfter,proto3" json:"RefreshAfter,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginResp) Reset()         { *m = LoginResp{} }
func (m *LoginResp) String() string { return proto.CompactTextString(m) }
func (*LoginResp) ProtoMessage()    {}
func (*LoginResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_7ce0b12f599e9f07, []int{7}
}

func (m *LoginResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginResp.Unmarshal(m, b)
}
func (m *LoginResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginResp.Marshal(b, m, deterministic)
}
func (m *LoginResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginResp.Merge(m, src)
}
func (m *LoginResp) XXX_Size() int {
	return xxx_messageInfo_LoginResp.Size(m)
}
func (m *LoginResp) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginResp.DiscardUnknown(m)
}

var xxx_messageInfo_LoginResp proto.InternalMessageInfo

func (m *LoginResp) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *LoginResp) GetCurrentAuthority() string {
	if m != nil {
		return m.CurrentAuthority
	}
	return ""
}

func (m *LoginResp) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *LoginResp) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *LoginResp) GetAccessToken() string {
	if m != nil {
		return m.AccessToken
	}
	return ""
}

func (m *LoginResp) GetAccessExpire() int64 {
	if m != nil {
		return m.AccessExpire
	}
	return 0
}

func (m *LoginResp) GetRefreshAfter() int64 {
	if m != nil {
		return m.RefreshAfter
	}
	return 0
}

func init() {
	proto.RegisterType((*UserCenterValidatePhoneReq)(nil), "oauth.UserCenterValidatePhoneReq")
	proto.RegisterType((*UserCenterValidatePhoneResp)(nil), "oauth.UserCenterValidatePhoneResp")
	proto.RegisterType((*UserCenterSendCodeReq)(nil), "oauth.UserCenterSendCodeReq")
	proto.RegisterType((*UserCenterSendCodeResp)(nil), "oauth.UserCenterSendCodeResp")
	proto.RegisterType((*SendCodeDataResp)(nil), "oauth.SendCodeDataResp")
	proto.RegisterType((*SendCodeDataResultResp)(nil), "oauth.SendCodeDataResultResp")
	proto.RegisterType((*LoginReq)(nil), "oauth.LoginReq")
	proto.RegisterType((*LoginResp)(nil), "oauth.loginResp")
}

func init() { proto.RegisterFile("oauth.proto", fileDescriptor_7ce0b12f599e9f07) }

var fileDescriptor_7ce0b12f599e9f07 = []byte{
	// 547 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x54, 0x4f, 0x8f, 0xd3, 0x3e,
	0x10, 0x55, 0x9a, 0xfe, 0x9d, 0xee, 0xef, 0xb7, 0x95, 0x05, 0x6d, 0xd4, 0xdd, 0x95, 0x4a, 0xb8,
	0x2c, 0x8b, 0xb4, 0x87, 0x22, 0xe0, 0x5c, 0x0a, 0x48, 0x48, 0x88, 0x3f, 0x61, 0xe1, 0x5a, 0x4c,
	0x3d, 0xdb, 0x46, 0xb4, 0x89, 0xd7, 0x63, 0x0b, 0x7a, 0xe0, 0xc8, 0x27, 0xe2, 0x33, 0x21, 0xf1,
	0x31, 0x50, 0x1c, 0xa7, 0x4d, 0x69, 0x0b, 0xb7, 0xbc, 0x37, 0xe3, 0x99, 0xa7, 0xf7, 0xec, 0x40,
	0x3b, 0xe5, 0x46, 0xcf, 0x2f, 0xa5, 0x4a, 0x75, 0xca, 0x6a, 0x16, 0x84, 0xcf, 0xa1, 0xff, 0x9e,
	0x50, 0x8d, 0x31, 0xd1, 0xa8, 0x3e, 0xf0, 0x45, 0x2c, 0xb8, 0xc6, 0x37, 0xf3, 0x34, 0xc1, 0x08,
	0x6f, 0x18, 0x83, 0xea, 0x34, 0x15, 0x18, 0x78, 0x03, 0xef, 0xbc, 0x15, 0xd9, 0x6f, 0x76, 0x0b,
	0x6a, 0x32, 0xab, 0x07, 0x15, 0x4b, 0xe6, 0x20, 0x7c, 0x0c, 0x27, 0x07, 0xe7, 0x90, 0x64, 0x01,
	0x34, 0xc8, 0x4c, 0xa7, 0x48, 0x64, 0x67, 0x35, 0xa3, 0x02, 0x86, 0x3f, 0x3c, 0xb8, 0xbd, 0x39,
	0xf9, 0x0e, 0x13, 0x31, 0x4e, 0x85, 0x5d, 0x7e, 0x02, 0x2d, 0xae, 0x90, 0x4f, 0x4a, 0x0a, 0x9a,
	0x19, 0x31, 0x3e, 0xa8, 0x82, 0xdd, 0x85, 0xff, 0x16, 0x3c, 0x99, 0x19, 0x3e, 0xc3, 0xfc, 0x98,
	0x6f, 0xab, 0x47, 0x05, 0x69, 0x8f, 0xf6, 0xa0, 0x61, 0x08, 0xd5, 0x24, 0x16, 0x41, 0xd5, 0x96,
	0xeb, 0x19, 0x7c, 0x21, 0xd8, 0x3d, 0xe8, 0xd0, 0x92, 0x9e, 0x18, 0x8a, 0x13, 0x24, 0x9a, 0xe8,
	0x95, 0xc4, 0xa0, 0x36, 0xf0, 0xce, 0xfd, 0xe8, 0xb8, 0xc4, 0x5f, 0xad, 0x24, 0x86, 0xdf, 0x3d,
	0xe8, 0xee, 0x53, 0x4d, 0x72, 0xcb, 0x33, 0xdf, 0x79, 0xd6, 0x01, 0x7f, 0x49, 0x33, 0xa7, 0x35,
	0xfb, 0x2c, 0x1b, 0xe2, 0x6f, 0x19, 0xc2, 0xee, 0x43, 0x55, 0x70, 0xcd, 0xad, 0xb6, 0xf6, 0xb0,
	0x77, 0x99, 0x87, 0x56, 0xac, 0x78, 0xca, 0x35, 0xcf, 0xd6, 0x44, 0xb6, 0x29, 0xfc, 0x06, 0x9d,
	0x3f, 0x2b, 0xeb, 0xd1, 0x28, 0xb6, 0xbc, 0x46, 0x91, 0x55, 0x96, 0x48, 0xc4, 0x67, 0x85, 0x6d,
	0x05, 0x64, 0x0f, 0xa1, 0xae, 0x90, 0xcc, 0x42, 0x5b, 0x35, 0xed, 0xe1, 0xd9, 0xfe, 0xb5, 0x66,
	0xa1, 0xed, 0x72, 0xd7, 0x1c, 0x3e, 0x82, 0xee, 0xfe, 0x0e, 0x76, 0x0a, 0x2d, 0x85, 0x37, 0x06,
	0x49, 0xc7, 0xc2, 0x85, 0xb7, 0x21, 0xc2, 0x31, 0x34, 0x5f, 0xa6, 0xb3, 0x38, 0x71, 0x31, 0xdb,
	0x38, 0x12, 0xbe, 0x5c, 0xc7, 0x9c, 0x11, 0xaf, 0xf8, 0x12, 0x59, 0x1f, 0x9a, 0x92, 0x13, 0x7d,
	0x49, 0x95, 0x70, 0x92, 0xd7, 0x38, 0xfc, 0xe9, 0x41, 0x6b, 0x91, 0x4f, 0x21, 0xc9, 0xba, 0x50,
	0x27, 0xcd, 0xb5, 0x21, 0x37, 0xc3, 0x21, 0x76, 0x01, 0x9d, 0xa9, 0x51, 0x0a, 0x13, 0x3d, 0x32,
	0x7a, 0x9e, 0xaa, 0x58, 0xaf, 0xdc, 0xa4, 0x1d, 0x9e, 0xfd, 0x0f, 0x95, 0x58, 0x58, 0x07, 0xfc,
	0xa8, 0x12, 0x8b, 0x6c, 0x7b, 0xa1, 0xc4, 0x5d, 0x95, 0x8d, 0xb2, 0x01, 0xb4, 0x47, 0x36, 0xb0,
	0xab, 0xf4, 0x33, 0x26, 0xf6, 0x9e, 0xb4, 0xa2, 0x32, 0xc5, 0x42, 0x38, 0xca, 0xe1, 0xb3, 0xaf,
	0x32, 0x56, 0x18, 0xd4, 0xed, 0xdc, 0x2d, 0x2e, 0xeb, 0x89, 0xf0, 0x5a, 0x21, 0xcd, 0x47, 0xd7,
	0x1a, 0x55, 0xd0, 0xc8, 0x7b, 0xca, 0xdc, 0xf0, 0x97, 0x07, 0xb5, 0xd7, 0x59, 0x1a, 0xec, 0x02,
	0x6a, 0xd6, 0x36, 0x76, 0xec, 0xe2, 0x29, 0x4c, 0xec, 0x77, 0x1c, 0xb1, 0xf1, 0xe3, 0x23, 0xf4,
	0x0e, 0x3c, 0x48, 0x76, 0xc7, 0x35, 0x1f, 0x7e, 0xf8, 0xfd, 0xf0, 0x5f, 0x2d, 0x24, 0xd9, 0x5b,
	0x60, 0xbb, 0x4f, 0x80, 0x9d, 0xee, 0x9c, 0x2c, 0xbd, 0xe9, 0xfe, 0xd9, 0x5f, 0xaa, 0x24, 0x3f,
	0xd5, 0xed, 0xbf, 0xe9, 0xc1, 0xef, 0x00, 0x00, 0x00, 0xff, 0xff, 0xc0, 0x99, 0x7c, 0x47, 0xaa,
	0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// OauthClient is the client API for Oauth service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type OauthClient interface {
	// Login 登录
	Login(ctx context.Context, in *LoginReq, opts ...grpc.CallOption) (*LoginResp, error)
	// 验证手机号是否注册过
	UserCenterValidatePhone(ctx context.Context, in *UserCenterValidatePhoneReq, opts ...grpc.CallOption) (*UserCenterValidatePhoneResp, error)
	// 发送验证码
	UserCenterSendCode(ctx context.Context, in *UserCenterSendCodeReq, opts ...grpc.CallOption) (*UserCenterSendCodeResp, error)
}

type oauthClient struct {
	cc *grpc.ClientConn
}

func NewOauthClient(cc *grpc.ClientConn) OauthClient {
	return &oauthClient{cc}
}

func (c *oauthClient) Login(ctx context.Context, in *LoginReq, opts ...grpc.CallOption) (*LoginResp, error) {
	out := new(LoginResp)
	err := c.cc.Invoke(ctx, "/oauth.Oauth/Login", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *oauthClient) UserCenterValidatePhone(ctx context.Context, in *UserCenterValidatePhoneReq, opts ...grpc.CallOption) (*UserCenterValidatePhoneResp, error) {
	out := new(UserCenterValidatePhoneResp)
	err := c.cc.Invoke(ctx, "/oauth.Oauth/UserCenterValidatePhone", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *oauthClient) UserCenterSendCode(ctx context.Context, in *UserCenterSendCodeReq, opts ...grpc.CallOption) (*UserCenterSendCodeResp, error) {
	out := new(UserCenterSendCodeResp)
	err := c.cc.Invoke(ctx, "/oauth.Oauth/UserCenterSendCode", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OauthServer is the server API for Oauth service.
type OauthServer interface {
	// Login 登录
	Login(context.Context, *LoginReq) (*LoginResp, error)
	// 验证手机号是否注册过
	UserCenterValidatePhone(context.Context, *UserCenterValidatePhoneReq) (*UserCenterValidatePhoneResp, error)
	// 发送验证码
	UserCenterSendCode(context.Context, *UserCenterSendCodeReq) (*UserCenterSendCodeResp, error)
}

// UnimplementedOauthServer can be embedded to have forward compatible implementations.
type UnimplementedOauthServer struct {
}

func (*UnimplementedOauthServer) Login(ctx context.Context, req *LoginReq) (*LoginResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Login not implemented")
}
func (*UnimplementedOauthServer) UserCenterValidatePhone(ctx context.Context, req *UserCenterValidatePhoneReq) (*UserCenterValidatePhoneResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UserCenterValidatePhone not implemented")
}
func (*UnimplementedOauthServer) UserCenterSendCode(ctx context.Context, req *UserCenterSendCodeReq) (*UserCenterSendCodeResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UserCenterSendCode not implemented")
}

func RegisterOauthServer(s *grpc.Server, srv OauthServer) {
	s.RegisterService(&_Oauth_serviceDesc, srv)
}

func _Oauth_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OauthServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/oauth.Oauth/Login",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OauthServer).Login(ctx, req.(*LoginReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Oauth_UserCenterValidatePhone_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserCenterValidatePhoneReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OauthServer).UserCenterValidatePhone(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/oauth.Oauth/UserCenterValidatePhone",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OauthServer).UserCenterValidatePhone(ctx, req.(*UserCenterValidatePhoneReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Oauth_UserCenterSendCode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserCenterSendCodeReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OauthServer).UserCenterSendCode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/oauth.Oauth/UserCenterSendCode",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OauthServer).UserCenterSendCode(ctx, req.(*UserCenterSendCodeReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _Oauth_serviceDesc = grpc.ServiceDesc{
	ServiceName: "oauth.Oauth",
	HandlerType: (*OauthServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Login",
			Handler:    _Oauth_Login_Handler,
		},
		{
			MethodName: "UserCenterValidatePhone",
			Handler:    _Oauth_UserCenterValidatePhone_Handler,
		},
		{
			MethodName: "UserCenterSendCode",
			Handler:    _Oauth_UserCenterSendCode_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "oauth.proto",
}
